/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-08-30 06:56:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bbs.BbsDAO;
import bbs.Bbs;
import java.util.ArrayList;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bbs.Bbs");
    _jspx_imports_classes.add("bbs.BbsDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.css\"> <!-- 참조  -->\r\n");
      out.write("    <title> 게시판 웹 사이트 - 검색 결과</title>\r\n");
      out.write("    \r\n");
      out.write("    <!--  핑테스트 팝업 창 띄우기 시작  -->\r\n");
      out.write("	<script>\r\n");
      out.write("    	function openPopupPingTest() {\r\n");
      out.write("       	 var popup = window.open(\"pingTest2.jsp\", \"_blank\", \"width=600,height=400\");\r\n");
      out.write("      	  popup.focus();\r\n");
      out.write(" 	   }\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write(" 	   function openPopupFindUser() {\r\n");
      out.write("  	      var popup = window.open(\"finduser.jsp\", \"_blank\", \"width=600,height=400\");\r\n");
      out.write("  	      popup.focus();\r\n");
      out.write(" 	   }\r\n");
      out.write("	</script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        a, a:hover {\r\n");
      out.write("            color: #000000;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
 
    // 검색어 가져오기
    String query = request.getParameter("query");
    // 검색어가 없을 경우 게시판 페이지로 리다이렉트
    if (query == null || query.isEmpty()) {
        response.sendRedirect("bbs.jsp");
        return;
    }
    
    // 사용자 정보 가져오기
    String userID = (String) session.getAttribute("userID");
    
    // 페이지 번호 가져오기
    int pageNumber = 1;
    if (request.getParameter("pageNumber") != null){
        pageNumber = Integer.parseInt(request.getParameter("pageNumber"));
    }
    
    // BbsDAO 인스턴스 생성
    BbsDAO bbsDAO = new BbsDAO();
    
    // 검색 결과 가져오기
    ArrayList<Bbs> searchResult = bbsDAO.searchList(query, pageNumber);
    
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"main.jsp\" style=\"margin-left: 10px;\">검색결과</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"main.jsp\">🛖메인</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"bbs.jsp\">📒게시판</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 if (userID == null) { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                        접속하기\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"join.jsp\">회원가입</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <li class=\"nav-item dropdown\">\r\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                            ⚙️회원관리\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-item\" onclick=\"openPopupFindUser(); return false;\">🏕️유저찾기</a>\r\n");
      out.write("						<a href=\"#\" class=\"dropdown-item\" onclick=\"openPopupPingTest(); return false;\">📡인터넷 테스트</a>\r\n");
      out.write("                            <a class=\"dropdown-item\" href=\"logoutAction.jsp\">🤚로그아웃</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row mt-4\">\r\n");
      out.write("    <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("        <h2 class=\"text-center\">게시글 검색</h2>\r\n");
      out.write("        <form action=\"search.jsp\" method=\"post\" class=\"text-right mt-4\">\r\n");
      out.write("            <div class=\"input-group\">\r\n");
      out.write("                <input type=\"text\" name=\"query\" placeholder=\"  검색어를 입력하세요\" class=\"form-control\" value=\"");
      out.print( query );
      out.write("\">\r\n");
      out.write("                <div class=\"input-group-append\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">검색🔍</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row mt-4\">\r\n");
      out.write("    <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("        <h2 class=\"text-middle\">검색 결과</h2>\r\n");
      out.write("        <p class=\"text-muted text-center\">검색어: ");
      out.print( query );
      out.write("</p>\r\n");
      out.write("        <table class=\"table table-bordered table-striped text-center\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>번호</th>\r\n");
      out.write("                    <th>제목</th>\r\n");
      out.write("                    <th>작성자</th>\r\n");
      out.write("                    <th>작성일</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 for (Bbs bbs : searchResult) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( bbs.getBbsID() );
      out.write("</td>\r\n");
      out.write("                    <td><a href=\"view.jsp?bbsID=");
      out.print( bbs.getBbsID() );
      out.write('"');
      out.write('>');
      out.print( bbs.getBbsTitle() );
      out.write("</a></td>\r\n");
      out.write("                    <td>");
      out.print( bbs.getUserID() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( bbs.getBbsDate().substring(0, 10) );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("            ");
 if (pageNumber != 1) { 
      out.write("\r\n");
      out.write("                <a href=\"search.jsp?query=");
      out.print( query );
      out.write("&pageNumber=");
      out.print( pageNumber - 1 );
      out.write("\" class=\"btn btn-success btn-arrow-left\">이전</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (bbsDAO.nextPage(pageNumber + 1)) { 
      out.write("\r\n");
      out.write("                <a href=\"search.jsp?query=");
      out.print( query );
      out.write("&pageNumber=");
      out.print( pageNumber + 1 );
      out.write("\" class=\"btn btn-success btn-arrow-right\">다음</a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
